CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35) NOT NULL,
  "password" varchar(35) NOT NULL,
  "age" int NOT NULL,
  "id_rol" int,
  "id_courses" int
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(35) UNIQUE NOT NULL,
  "description" varchar(35),
  "id_level" int,
  "id_category" int
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) NOT NULL
);

CREATE TABLE "level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(15) NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(35) NOT NULL
);

ALTER TABLE "users" ADD FOREIGN KEY ("id_courses") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_level") REFERENCES "level" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("id_category") REFERENCES "categories" ("id");

ALTER TABLE "users" ADD FOREIGN KEY ("id_rol") REFERENCES "roles" ("id");



INSERT INTO roles VALUES (1, 'Student'), (2, 'Teacher'), (3, 'Admin');
INSERT INTO level VALUES (1, 'Beginner'), (2, 'intermediate'), (3, 'Advanced');
INSERT INTO categories VALUES (1, 'Python'), (2, 'Databases');
INSERT INTO courses VALUES (1, 'Python de 0 a experto', 'Curso de python', 1, 1), (2, 'PostgreSQL para principiantes', 'Curso de PostgreSQL', 1, 2);
INSERT INTO users VALUES (1, 'Angel Herrera', 'password123', 27, 1, 1), (2, 'Ian Rosas', 'pass', 28, 2, 2);
